package com.questua.app.presentation.admin.content.questpoints

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AddPhotoAlternate
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.LocationCity
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage
import coil.request.ImageRequest
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.common.toFullImageUrl
import com.questua.app.core.ui.components.*
import com.questua.app.domain.model.City
import com.questua.app.domain.model.QuestPoint
import com.questua.app.domain.model.UnlockRequirement
import com.questua.app.presentation.admin.content.ai.SelectorDialog
import java.io.File

@Composable
fun QuestPointFormDialog(
    questPoint: QuestPoint? = null,
    cities: List<City>,
    onDismiss: () -> Unit,
    onConfirm: (
        title: String, cityId: String, desc: String, difficulty: Int,
        lat: Double, lon: Double, img: File?, icon: File?,
        unlock: UnlockRequirement?, isPremium: Boolean, isAi: Boolean, isPub: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    var title by remember { mutableStateOf(questPoint?.title ?: "") }
    var description by remember { mutableStateOf(questPoint?.description ?: "") }
    var cityId by remember { mutableStateOf(questPoint?.cityId ?: "") }
    var difficulty by remember { mutableStateOf(questPoint?.difficulty?.toFloat() ?: 1f) }
    var lat by remember { mutableStateOf(questPoint?.lat?.toString() ?: "") }
    var lon by remember { mutableStateOf(questPoint?.lon?.toString() ?: "") }
    var isPremium by remember { mutableStateOf(questPoint?.isPremium ?: false) }
    var isPublished by remember { mutableStateOf(questPoint?.isPublished ?: true) }
    var isAiGenerated by remember { mutableStateOf(questPoint?.isAiGenerated ?: false) }

    var selectedImageFile by remember { mutableStateOf<File?>(null) }
    var selectedIconFile by remember { mutableStateOf<File?>(null) }
    var selectedImageUri by remember { mutableStateOf<Uri?>(null) }
    var selectedIconUri by remember { mutableStateOf<Uri?>(null) }

    var reqPremium by remember { mutableStateOf(questPoint?.unlockRequirement?.premiumAccess ?: false) }
    var reqLevel by remember { mutableStateOf(questPoint?.unlockRequirement?.requiredGamificationLevel?.toString() ?: "") }
    var reqCefr by remember { mutableStateOf(questPoint?.unlockRequirement?.requiredCefrLevel ?: "") }

    var showCityPicker by remember { mutableStateOf(false) }

    // Validation states
    var titleError by remember { mutableStateOf<String?>(null) }
    var latError by remember { mutableStateOf<String?>(null) }
    var lonError by remember { mutableStateOf<String?>(null) }

    val imagePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let {
            selectedImageUri = it
            selectedImageFile = URIPathHelper.getFileFromUri(context, it)
        }
    }
    val iconPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let {
            selectedIconUri = it
            selectedIconFile = URIPathHelper.getFileFromUri(context, it)
        }
    }

    fun validate(): Boolean {
        var isValid = true
        if (title.isBlank()) { titleError = "Obrigatório"; isValid = false } else titleError = null

        if (lat.isNotBlank() && lat.toDoubleOrNull() == null) {
            latError = "Número inválido"; isValid = false
        } else latError = null

        if (lon.isNotBlank() && lon.toDoubleOrNull() == null) {
            lonError = "Número inválido"; isValid = false
        } else lonError = null

        return isValid
    }

    QuestuaBaseFormDialog(
        title = if (questPoint == null) "Novo Ponto de Quest" else "Editar Ponto",
        onDismiss = onDismiss,
        onConfirm = {
            if (validate()) {
                val unlock = UnlockRequirement(
                    premiumAccess = reqPremium,
                    requiredGamificationLevel = reqLevel.toIntOrNull(),
                    requiredCefrLevel = reqCefr.ifEmpty { null }
                )
                onConfirm(
                    title, cityId, description, difficulty.toInt(),
                    lat.toDoubleOrNull() ?: 0.0, lon.toDoubleOrNull() ?: 0.0,
                    selectedImageFile, selectedIconFile,
                    unlock, isPremium, isAiGenerated, isPublished
                )
            }
        },
        confirmEnabled = title.isNotBlank() && cityId.isNotBlank()
    ) {
        FormSectionTitle("Identidade Visual")
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            ImageSelectorBox(
                modifier = Modifier.weight(1f),
                label = "Capa",
                uri = selectedImageUri,
                fallbackUrl = questPoint?.imageUrl,
                icon = Icons.Default.AddPhotoAlternate,
                onClick = { imagePicker.launch("image/*") }
            )
            ImageSelectorBox(
                modifier = Modifier.weight(1f),
                label = "Ícone Mapa",
                uri = selectedIconUri,
                fallbackUrl = questPoint?.iconUrl,
                icon = Icons.Default.Image,
                contentScale = ContentScale.Fit,
                onClick = { iconPicker.launch("image/*") }
            )
        }

        FormSectionTitle("Localização e Contexto")
        QuestuaTextField(value = title, onValueChange = { title = it; titleError = null }, label = "Título do Ponto", errorMessage = titleError)

        QuestuaSelectorField(
            label = "Cidade Vinculada",
            value = cities.find { it.id == cityId }?.name ?: "Selecionar Cidade",
            icon = Icons.Default.LocationCity,
            onClick = { showCityPicker = true },
            isPlaceholder = cityId.isEmpty()
        )

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(Modifier.weight(1f)) { QuestuaTextField(value = lat, onValueChange = { lat = it; latError = null }, label = "Latitude", errorMessage = latError) }
            Box(Modifier.weight(1f)) { QuestuaTextField(value = lon, onValueChange = { lon = it; lonError = null }, label = "Longitude", errorMessage = lonError) }
        }

        FormSectionTitle("Detalhes e Dificuldade")
        QuestuaTextField(value = description, onValueChange = { description = it }, label = "Descrição")

        Column(modifier = Modifier.padding(horizontal = 4.dp)) {
            Text(
                text = "Nível de Dificuldade: ${difficulty.toInt()}",
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.primary,
                fontWeight = FontWeight.Bold
            )
            Slider(
                value = difficulty,
                onValueChange = { difficulty = it },
                valueRange = 1f..5f,
                steps = 3
            )
        }

        FormSectionTitle("Requisitos de Acesso")
        Surface(
            color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
            shape = RoundedCornerShape(16.dp)
        ) {
            Column(Modifier.padding(8.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = reqPremium, onCheckedChange = { reqPremium = it })
                    Text("Exigir Assinatura Premium", style = MaterialTheme.typography.bodyMedium)
                }
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = reqLevel, onValueChange = { reqLevel = it.filter { char -> char.isDigit() } }, label = "Nível Mín.") }
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = reqCefr, onValueChange = { reqCefr = it.uppercase().take(2) }, label = "CEFR (ex: B2)") }
                }
            }
        }

        FormSectionTitle("Status de Publicação")
        Surface(
            color = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.15f),
            shape = RoundedCornerShape(16.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth().padding(8.dp),
                horizontalArrangement = Arrangement.SpaceEvenly
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isPublished, onCheckedChange = { isPublished = it })
                    Text("Publicado", style = MaterialTheme.typography.bodySmall)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isPremium, onCheckedChange = { isPremium = it })
                    Text("Premium", style = MaterialTheme.typography.bodySmall)
                }
            }
        }
    }

    if (showCityPicker) {
        SelectorDialog(
            title = "Selecione a Cidade",
            items = cities,
            itemContent = { Text(it.name, fontWeight = FontWeight.Bold) },
            onSelect = { cityId = it.id; showCityPicker = false },
            onDismiss = { showCityPicker = false }
        )
    }
}

@Composable
private fun ImageSelectorBox(
    modifier: Modifier,
    label: String,
    uri: Uri?,
    fallbackUrl: String?,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    contentScale: ContentScale = ContentScale.Crop,
    onClick: () -> Unit
) {
    Box(
        modifier = modifier
            .height(110.dp)
            .clip(RoundedCornerShape(16.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
            .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(16.dp))
            .clickable { onClick() },
        contentAlignment = Alignment.Center
    ) {
        val model = uri ?: fallbackUrl?.toFullImageUrl()
        if (model != null) {
            AsyncImage(
                model = ImageRequest.Builder(LocalContext.current).data(model).crossfade(true).build(),
                contentDescription = null,
                contentScale = contentScale,
                modifier = Modifier.fillMaxSize()
            )
        } else {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Icon(icon, null, tint = MaterialTheme.colorScheme.primary)
                Text(label, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
        }
    }
}