package com.questua.app.presentation.admin.content.characters

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.Mic
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.ui.components.FormSectionTitle
import com.questua.app.core.ui.components.QuestuaBaseFormDialog
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.model.CharacterEntity
import com.questua.app.domain.model.Persona
import com.questua.app.core.ui.components.*
import java.io.File

@Composable
fun CharacterFormDialog(
    character: CharacterEntity? = null,
    onDismiss: () -> Unit,
    onConfirm: (
        name: String, avatar: Any?, voice: Any?,
        sprites: List<Any>,
        persona: Persona?, isAi: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    var name by remember { mutableStateOf(character?.name ?: "") }
    var isAiGenerated by remember { mutableStateOf(character?.isAiGenerated ?: false) }
    var avatar by remember { mutableStateOf<Any?>(character?.avatarUrl) }
    var voice by remember { mutableStateOf<Any?>(character?.voiceUrl) }
    val spriteUrls = remember { mutableStateListOf<Any>().apply { addAll(character?.spriteSheet?.urls ?: emptyList()) } }

    var pDesc by remember { mutableStateOf(character?.persona?.description ?: "") }
    var pStyle by remember { mutableStateOf(character?.persona?.speakingStyle ?: "") }
    var pTone by remember { mutableStateOf(character?.persona?.voiceTone ?: "") }
    var pBack by remember { mutableStateOf(character?.persona?.background ?: "") }
    val pTraits = remember { mutableStateListOf<String>().apply { addAll(character?.persona?.traits ?: emptyList()) } }

    // Validation
    var nameError by remember { mutableStateOf<String?>(null) }

    val avatarPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { avatar = URIPathHelper.getFileFromUri(context, it) }
    }
    val voicePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { voice = URIPathHelper.getFileFromUri(context, it) }
    }
    val spritePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { URIPathHelper.getFileFromUri(context, it)?.let { file -> spriteUrls.add(file) } }
    }

    fun validate(): Boolean {
        var isValid = true
        if (name.isBlank()) { nameError = "Obrigatório"; isValid = false } else nameError = null
        return isValid
    }

    QuestuaBaseFormDialog(
        title = if (character == null) "Novo Personagem" else "Editar Personagem",
        onDismiss = onDismiss,
        onConfirm = {
            if (validate()) {
                val finalPersona = if (pDesc.isBlank() && pTraits.isEmpty()) null else Persona(
                    description = pDesc.ifBlank { null },
                    traits = pTraits.filter { it.isNotBlank() },
                    speakingStyle = pStyle.ifBlank { null },
                    voiceTone = pTone.ifBlank { null },
                    background = pBack.ifBlank { null }
                )
                onConfirm(name, avatar, voice, spriteUrls, finalPersona, isAiGenerated)
            }
        },
        confirmEnabled = name.isNotBlank() && avatar != null
    ) {
        FormSectionTitle("Informações Básicas")
        QuestuaTextField(value = name, onValueChange = { name = it; nameError = null }, label = "Nome do Personagem", errorMessage = nameError)

        Surface(
            color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f),
            shape = RoundedCornerShape(12.dp)
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 12.dp, vertical = 4.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Checkbox(
                    checked = isAiGenerated,
                    onCheckedChange = { isAiGenerated = it }
                )
                Text("Gerado por Inteligência Artificial", style = MaterialTheme.typography.bodyMedium)
            }
        }

        FormSectionTitle("Assets & Mídia")
        MediaPickerField(
            label = "Avatar (Imagem)",
            value = avatar,
            icon = Icons.Default.Image,
            onPick = { avatarPicker.launch("image/*") },
            onClear = { avatar = null }
        )

        MediaPickerField(
            label = "Voz (Áudio)",
            value = voice,
            icon = Icons.Default.Mic,
            onPick = { voicePicker.launch("audio/*") },
            onClear = { voice = null }
        )

        ExpandableListSection(
            title = "Sprite Sheet (${spriteUrls.size})",
            onAdd = { spritePicker.launch("image/*") }
        ) {
            spriteUrls.forEachIndexed { index, item ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
                        .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(12.dp))
                        .padding(12.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = if(item is File) "Arquivo: ${item.name}" else "URL: $item",
                        style = MaterialTheme.typography.bodySmall,
                        modifier = Modifier.weight(1f),
                        maxLines = 1
                    )
                    IconButton(onClick = { spriteUrls.removeAt(index) }, modifier = Modifier.size(24.dp)) {
                        Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error)
                    }
                }
            }
        }

        HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp), color = MaterialTheme.colorScheme.outlineVariant)

        FormSectionTitle("Persona")
        QuestuaTextField(value = pDesc, onValueChange = { pDesc = it }, label = "Descrição")
        QuestuaTextField(value = pBack, onValueChange = { pBack = it }, label = "Background / História")

        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(Modifier.weight(1f)) { QuestuaTextField(value = pStyle, onValueChange = { pStyle = it }, label = "Estilo") }
            Box(Modifier.weight(1f)) { QuestuaTextField(value = pTone, onValueChange = { pTone = it }, label = "Tom") }
        }

        ExpandableListSection(
            title = "Traços (${pTraits.size})",
            onAdd = { pTraits.add("") }
        ) {
            pTraits.forEachIndexed { index, trait ->
                Row(
                    modifier = Modifier.padding(vertical = 4.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    QuestuaTextField(
                        value = trait,
                        onValueChange = { pTraits[index] = it },
                        label = "Traço ${index + 1}",
                        modifier = Modifier.weight(1f)
                    )
                    IconButton(onClick = { pTraits.removeAt(index) }) {
                        Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error)
                    }
                }
            }
        }
    }
}