package com.questua.app.domain.enums

enum class AchievementConditionType {
    COMPLETE_SPECIFIC_QUEST,
    COMPLETE_QUEST_AMOUNT,
    REACH_GAMIFICATION_LEVEL,
    UNLOCK_CITY_AMOUNT,
    UNLOCK_QUEST_POINT_AMOUNT,
    EARN_XP_AMOUNT,
    REACH_CEFR_LEVEL,
    LEARN_LANGUAGE_AMOUNT,
    STREAK_DAYS_AMOUNT,
    PERFECT_QUEST_COMPLETION,
    COMPLETE_ALL_CITY_QUESTS,
    FAST_QUEST_COMPLETION,
    SUBMIT_FEEDBACK,
    UNLOCK_PREMIUM_CONTENT
}