package com.questua.app.presentation.admin.content.quests

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChatBubbleOutline
import androidx.compose.material.icons.filled.MyLocation
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.ui.components.*
import com.questua.app.domain.model.LearningFocus
import com.questua.app.domain.model.Quest
import com.questua.app.domain.model.QuestPoint
import com.questua.app.domain.model.SceneDialogue
import com.questua.app.domain.model.UnlockRequirement

@Composable
fun QuestFormDialog(
    quest: Quest? = null,
    questPoints: List<QuestPoint>,
    dialogues: List<SceneDialogue>,
    onDismiss: () -> Unit,
    onConfirm: (
        title: String, qpId: String, dialId: String?, desc: String,
        diff: Int, order: Int, xpValue: Int, xpPerQuestion: Int,
        unlock: UnlockRequirement?, focus: LearningFocus?,
        prem: Boolean, ai: Boolean, pub: Boolean
    ) -> Unit
) {
    var title by remember { mutableStateOf(quest?.title ?: "") }
    var description by remember { mutableStateOf(quest?.description ?: "") }
    var questPointId by remember { mutableStateOf(quest?.questPointId ?: "") }
    var firstDialogueId by remember { mutableStateOf(quest?.firstDialogueId ?: "") }

    var difficulty by remember { mutableStateOf(quest?.difficulty?.toFloat() ?: 1f) }
    var orderIndex by remember { mutableStateOf(quest?.orderIndex?.toString() ?: "1") }

    var xpValue by remember { mutableStateOf(quest?.xpValue?.toString() ?: "0") }
    var xpPerQuestion by remember { mutableStateOf(quest?.xpPerQuestion?.toString() ?: "10") }

    var grammar by remember { mutableStateOf(quest?.learningFocus?.grammarTopics?.joinToString(", ") ?: "") }
    var vocabulary by remember { mutableStateOf(quest?.learningFocus?.vocabularyThemes?.joinToString(", ") ?: "") }
    var skills by remember { mutableStateOf(quest?.learningFocus?.skills?.joinToString(", ") ?: "") }

    var isPremium by remember { mutableStateOf(quest?.isPremium ?: false) }
    var isPublished by remember { mutableStateOf(quest?.isPublished ?: true) }
    var isAiGenerated by remember { mutableStateOf(quest?.isAiGenerated ?: false) }

    var reqPremium by remember { mutableStateOf(quest?.unlockRequirement?.premiumAccess ?: false) }
    var reqLevel by remember { mutableStateOf(quest?.unlockRequirement?.requiredGamificationLevel?.toString() ?: "") }
    var reqCefr by remember { mutableStateOf(quest?.unlockRequirement?.requiredCefrLevel ?: "") }

    var showQpPicker by remember { mutableStateOf(false) }
    var showDialoguePicker by remember { mutableStateOf(false) }

    // Validation states
    var titleError by remember { mutableStateOf<String?>(null) }
    var xpValueError by remember { mutableStateOf<String?>(null) }
    var xpPerQuestionError by remember { mutableStateOf<String?>(null) }

    fun validate(): Boolean {
        var isValid = true
        if (title.isBlank()) { titleError = "Obrigatório"; isValid = false } else titleError = null

        if (xpValue.isNotBlank() && xpValue.toIntOrNull() == null) {
            xpValueError = "Valor inválido"; isValid = false
        } else xpValueError = null

        if (xpPerQuestion.isNotBlank() && xpPerQuestion.toIntOrNull() == null) {
            xpPerQuestionError = "Valor inválido"; isValid = false
        } else xpPerQuestionError = null

        return isValid
    }

    QuestuaBaseFormDialog(
        title = if (quest == null) "Nova Missão" else "Editar Missão",
        onDismiss = onDismiss,
        onConfirm = {
            if (validate()) {
                val unlock = UnlockRequirement(
                    premiumAccess = reqPremium,
                    requiredGamificationLevel = reqLevel.toIntOrNull(),
                    requiredCefrLevel = reqCefr.ifEmpty { null }
                )

                val focus = LearningFocus(
                    grammarTopics = grammar.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null },
                    vocabularyThemes = vocabulary.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null },
                    skills = skills.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null }
                )

                onConfirm(
                    title, questPointId, firstDialogueId.ifEmpty { null }, description,
                    difficulty.toInt(), orderIndex.toIntOrNull() ?: 1,
                    xpValue.trim().toIntOrNull() ?: 0, xpPerQuestion.trim().toIntOrNull() ?: 10,
                    unlock, focus, isPremium, isAiGenerated, isPublished
                )
            }
        },
        confirmEnabled = title.isNotBlank() && questPointId.isNotBlank()
    ) {
        FormSectionTitle("Dados da Missão")
        QuestuaTextField(value = title, onValueChange = { title = it; titleError = null }, label = "Título da Quest", errorMessage = titleError)
        QuestuaTextField(value = description, onValueChange = { description = it }, label = "Descrição Narrativa")

        FormSectionTitle("Vínculos")
        QuestuaSelectorField(
            label = "Quest Point (Local)",
            value = questPoints.find { it.id == questPointId }?.title ?: "Selecionar Local",
            icon = Icons.Default.MyLocation,
            onClick = { showQpPicker = true },
            isPlaceholder = questPointId.isEmpty()
        )

        QuestuaSelectorField(
            label = "Diálogo Inicial (Cena)",
            value = dialogues.find { it.id == firstDialogueId }?.textContent?.take(30)?.plus("...") ?: "Nenhum Diálogo",
            icon = Icons.Default.ChatBubbleOutline,
            onClick = { showDialoguePicker = true },
            isPlaceholder = firstDialogueId.isEmpty()
        )

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(Modifier.weight(1f)) {
                QuestuaTextField(value = orderIndex, onValueChange = { orderIndex = it.filter { char -> char.isDigit() } }, label = "Ordem na Cidade")
            }
            Box(Modifier.weight(1f)) {
                Column {
                    Text("Dificuldade: ${difficulty.toInt()}", style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold)
                    Slider(value = difficulty, onValueChange = { difficulty = it }, valueRange = 1f..5f, steps = 3)
                }
            }
        }

        FormSectionTitle("Gamificação & XP")
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(Modifier.weight(1f)) { QuestuaTextField(value = xpValue, onValueChange = { xpValue = it.filter { char -> char.isDigit() }; xpValueError = null }, label = "XP Base", errorMessage = xpValueError) }
            Box(Modifier.weight(1f)) { QuestuaTextField(value = xpPerQuestion, onValueChange = { xpPerQuestion = it.filter { char -> char.isDigit() }; xpPerQuestionError = null }, label = "XP p/ Acerto", errorMessage = xpPerQuestionError) }
        }

        FormSectionTitle("Foco Pedagógico")
        QuestuaTextField(value = grammar, onValueChange = { grammar = it }, label = "Tópicos de Gramática")
        QuestuaTextField(value = vocabulary, onValueChange = { vocabulary = it }, label = "Temas de Vocabulário")
        QuestuaTextField(value = skills, onValueChange = { skills = it }, label = "Habilidades (Listening, Reading...)")

        FormSectionTitle("Regras de Acesso")
        Surface(color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f), shape = RoundedCornerShape(16.dp)) {
            Column(Modifier.padding(8.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = reqPremium, onCheckedChange = { reqPremium = it })
                    Text("Obrigatório para Premium", style = MaterialTheme.typography.bodyMedium)
                }
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = reqLevel, onValueChange = { reqLevel = it.filter { char -> char.isDigit() } }, label = "Nível Mín.") }
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = reqCefr, onValueChange = { reqCefr = it.uppercase().take(2) }, label = "CEFR (ex: B1)") }
                }
            }
        }

        FormSectionTitle("Visibilidade")
        Surface(color = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.15f), shape = RoundedCornerShape(16.dp)) {
            Row(modifier = Modifier.fillMaxWidth().padding(8.dp), horizontalArrangement = Arrangement.SpaceEvenly) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isPublished, onCheckedChange = { isPublished = it })
                    Text("Publicado", style = MaterialTheme.typography.bodySmall)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isPremium, onCheckedChange = { isPremium = it })
                    Text("Premium", style = MaterialTheme.typography.bodySmall)
                }
            }
        }
    }

    if (showQpPicker) {
        SelectorDialog(
            title = "Selecione o Local",
            items = questPoints,
            itemContent = { qp -> Text(qp.title, fontWeight = FontWeight.Bold) },
            onSelect = { questPointId = it.id; showQpPicker = false },
            onDismiss = { showQpPicker = false }
        )
    }

    if (showDialoguePicker) {
        SelectorDialog(
            title = "Cena de Abertura",
            items = dialogues,
            itemContent = { d -> Text(d.textContent.take(50), fontWeight = FontWeight.Medium) },
            onSelect = { firstDialogueId = it.id; showDialoguePicker = false },
            onDismiss = { showDialoguePicker = false },
            canClear = true,
            onClear = { firstDialogueId = ""; showDialoguePicker = false }
        )
    }
}