package com.questua.app.presentation.admin.content.dialogues

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.ui.components.*
import com.questua.app.domain.enums.InputMode
import com.questua.app.domain.model.*
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SceneDialogueFormDialog(
    dialogue: SceneDialogue? = null,
    characters: List<CharacterEntity>,
    allDialogues: List<SceneDialogue>,
    onDismiss: () -> Unit,
    onConfirm: (
        txt: String, desc: String,
        bg: Any?, music: Any?,
        states: List<CharacterState>?, effects: List<SceneEffect>?,
        speaker: String?,
        audio: Any?,
        expects: Boolean,
        mode: InputMode, expectResp: String?, choices: List<Choice>?,
        next: String?, ai: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    var description by remember { mutableStateOf(dialogue?.description ?: "") }
    var textContent by remember { mutableStateOf(dialogue?.textContent ?: "") }
    var background by remember { mutableStateOf<Any?>(dialogue?.backgroundUrl) }
    var bgMusic by remember { mutableStateOf<Any?>(dialogue?.bgMusicUrl) }
    var audio by remember { mutableStateOf<Any?>(dialogue?.audioUrl) }
    var speakerId by remember { mutableStateOf(dialogue?.speakerCharacterId ?: "") }
    var nextDialogueId by remember { mutableStateOf(dialogue?.nextDialogueId ?: "") }
    var inputMode by remember { mutableStateOf(dialogue?.inputMode ?: InputMode.NONE) }
    var expectsUserResponse by remember { mutableStateOf(dialogue?.expectsUserResponse ?: false) }
    var expectedResponse by remember { mutableStateOf(dialogue?.expectedResponse ?: "") }
    var isAiGenerated by remember { mutableStateOf(dialogue?.isAiGenerated ?: false) }

    val characterStates = remember { mutableStateListOf<CharacterState>().apply { addAll(dialogue?.characterStates ?: emptyList()) } }
    val sceneEffects = remember { mutableStateListOf<SceneEffect>().apply { addAll(dialogue?.sceneEffects ?: emptyList()) } }
    val choices = remember { mutableStateListOf<Choice>().apply { addAll(dialogue?.choices ?: emptyList()) } }

    var showSpeakerPicker by remember { mutableStateOf(false) }
    var showNextDialogPicker by remember { mutableStateOf(false) }
    var showStateCharPicker by remember { mutableStateOf<Int?>(null) }
    var showChoiceDialogPicker by remember { mutableStateOf<Int?>(null) }

    // Validation
    var textContentError by remember { mutableStateOf<String?>(null) }

    val bgPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { background = URIPathHelper.getFileFromUri(context, it) }
    }
    val musicPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { bgMusic = URIPathHelper.getFileFromUri(context, it) }
    }
    val audioPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { audio = URIPathHelper.getFileFromUri(context, it) }
    }

    fun validate(): Boolean {
        var isValid = true
        if (textContent.isBlank()) { textContentError = "O texto é obrigatório"; isValid = false } else textContentError = null
        return isValid
    }

    QuestuaBaseFormDialog(
        title = if (dialogue == null) "Nova Cena" else "Editar Cena",
        onDismiss = onDismiss,
        onConfirm = {
            if (validate()) {
                onConfirm(
                    textContent, description, background, bgMusic,
                    characterStates.toList().ifEmpty { null },
                    sceneEffects.toList().ifEmpty { null },
                    speakerId.ifEmpty { null }, audio,
                    expectsUserResponse, inputMode, expectedResponse.ifEmpty { null },
                    choices.toList().ifEmpty { null }, nextDialogueId.ifEmpty { null }, isAiGenerated
                )
            }
        },
        confirmEnabled = textContent.isNotBlank()
    ) {
        FormSectionTitle("Informações Gerais")
        QuestuaTextField(value = description, onValueChange = { description = it }, label = "Identificador Interno (Opcional)")
        QuestuaTextField(value = textContent, onValueChange = { textContent = it; textContentError = null }, label = "Texto da Cena", errorMessage = textContentError)

        FormSectionTitle("Ambiente & Mídia")
        MediaPickerField(
            label = "Cenário (Imagem de Fundo)",
            value = background,
            icon = Icons.Default.Image,
            onPick = { bgPicker.launch("image/*") },
            onClear = { background = null }
        )

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Box(Modifier.weight(1f)) {
                MediaPickerField(label = "Música (Ambiente)", value = bgMusic, icon = Icons.Default.MusicNote, onPick = { musicPicker.launch("audio/*") }, onClear = { bgMusic = null })
            }
            Box(Modifier.weight(1f)) {
                MediaPickerField(label = "Voz (Dublagem)", value = audio, icon = Icons.Default.Mic, onPick = { audioPicker.launch("audio/*") }, onClear = { audio = null })
            }
        }

        FormSectionTitle("Narrativa")
        QuestuaSelectorField(
            label = "Quem fala?",
            value = characters.find { it.id == speakerId }?.name ?: "Narrador / Nenhum",
            icon = Icons.Default.Person,
            onClick = { showSpeakerPicker = true },
            isPlaceholder = speakerId.isEmpty()
        )

        FormSectionTitle("Interação")
        QuestuaEnumDropdown(
            label = "Modo de Entrada",
            options = InputMode.entries.toTypedArray(),
            selectedOption = inputMode,
            onOptionSelected = { inputMode = it }
        )

        Surface(color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f), shape = RoundedCornerShape(16.dp)) {
            Row(modifier = Modifier.fillMaxWidth().padding(horizontal = 8.dp), verticalAlignment = Alignment.CenterVertically) {
                Checkbox(checked = expectsUserResponse, onCheckedChange = { expectsUserResponse = it })
                Text("Aguarda Resposta", style = MaterialTheme.typography.bodyMedium)
                if (expectsUserResponse) {
                    Spacer(Modifier.width(8.dp))
                    Box(Modifier.weight(1f)) {
                        QuestuaTextField(value = expectedResponse, onValueChange = { expectedResponse = it }, label = "Resposta")
                    }
                }
            }
        }

        QuestuaSelectorField(
            label = "Próxima Cena",
            value = allDialogues.find { it.id == nextDialogueId }?.textContent?.take(30) ?: "Finalizar Cena",
            icon = Icons.Default.ArrowForward,
            onClick = { showNextDialogPicker = true },
            isPlaceholder = nextDialogueId.isEmpty()
        )

        FormSectionTitle("Composição da Cena")
        ExpandableListSection(title = "Atores em Cena (${characterStates.size})", onAdd = { characterStates.add(CharacterState("", "NORMAL", "CENTER")) }) {
            characterStates.forEachIndexed { index, state ->
                Column(Modifier.padding(vertical = 4.dp).clip(RoundedCornerShape(12.dp)).background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)).border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(12.dp)).padding(12.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        val name = characters.find { it.id == state.characterId }?.name ?: "Selecionar Ator..."
                        Text(name, style = MaterialTheme.typography.labelMedium, fontWeight = FontWeight.Bold, modifier = Modifier.weight(1f))
                        IconButton(onClick = { characterStates.removeAt(index) }, modifier = Modifier.size(24.dp)) {
                            Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error)
                        }
                    }
                    TextButton(onClick = { showStateCharPicker = index }, contentPadding = PaddingValues(0.dp)) { Text("Trocar Personagem") }
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        QuestuaTextField(value = state.expression ?: "", onValueChange = { characterStates[index] = state.copy(expression = it) }, label = "Expressão", modifier = Modifier.weight(1f))
                        QuestuaTextField(value = state.position ?: "", onValueChange = { characterStates[index] = state.copy(position = it) }, label = "Posição", modifier = Modifier.weight(1f))
                    }
                }
            }
        }

        ExpandableListSection(title = "Opções/Escolhas (${choices.size})", onAdd = { choices.add(Choice("", null)) }) {
            choices.forEachIndexed { index, choice ->
                Column(Modifier.padding(vertical = 4.dp).clip(RoundedCornerShape(12.dp)).background(MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.1f)).border(1.dp, MaterialTheme.colorScheme.primary.copy(alpha = 0.1f), RoundedCornerShape(12.dp)).padding(12.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        QuestuaTextField(value = choice.text, onValueChange = { choices[index] = choice.copy(text = it) }, label = "Texto da Opção", modifier = Modifier.weight(1f))
                        IconButton(onClick = { choices.removeAt(index) }) { Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error) }
                    }
                    val nextName = allDialogues.find { it.id == choice.nextDialogueId }?.textContent?.take(20) ?: "Nenhum"
                    TextButton(onClick = { showChoiceDialogPicker = index }) { Text("Vai para: $nextName") }
                }
            }
        }
    }

    if (showSpeakerPicker) {
        SelectorDialog("Quem fala?", characters, { Text(it.name, fontWeight = FontWeight.Bold) }, { speakerId = it.id; showSpeakerPicker = false }, { showSpeakerPicker = false }, true, { speakerId = ""; showSpeakerPicker = false })
    }
    if (showNextDialogPicker) {
        SelectorDialog("Sequência", allDialogues, { Text(it.textContent.take(50), fontWeight = FontWeight.Medium) }, { nextDialogueId = it.id; showNextDialogPicker = false }, { showNextDialogPicker = false }, true, { nextDialogueId = ""; showNextDialogPicker = false })
    }
    showStateCharPicker?.let { idx ->
        SelectorDialog("Ator", characters, { Text(it.name, fontWeight = FontWeight.Bold) }, { characterStates[idx] = characterStates[idx].copy(characterId = it.id); showStateCharPicker = null }, { showStateCharPicker = null })
    }
    showChoiceDialogPicker?.let { idx ->
        SelectorDialog("Destino", allDialogues, { Text(it.textContent.take(40), fontWeight = FontWeight.Medium) }, { choices[idx] = choices[idx].copy(nextDialogueId = it.id); showChoiceDialogPicker = null }, { showChoiceDialogPicker = null }, true, { choices[idx] = choices[idx].copy(nextDialogueId = null); showChoiceDialogPicker = null })
    }
}